[package]
name = "datamodel"
version = "0.6.0"
edition = "2021"
authors = ["Jakobg1215"]
description = "A rust library to serialize and deserialize Valve's proprietary DMX file format."
repository = "https://github.com/Jakobg1215/datamodel-rs/"
license = "MIT"
keywords = ["valve", "source-engine", "datamodel"]
categories = ["parser-implementations"]
readme = "README.md"
exclude = ["tests/*"]

[dependencies]
indexmap = "2.2.6"
regex = "1.10.4"
thiserror = "1.0.60"
uuid = { version = "1.8.0", features = ["v4", "rng", "fast-rng"] }
