[package]
name = "datamodel"
version = "0.5.1"
edition = "2021"
authors = ["Jakobg1215"]
description = "A rust library to serialize and deserialize Valve's proprietary DMX file format."
repository = "https://github.com/Jakobg1215/datamodel-rs/"
license = "MIT"
keywords = ["valve", "source-engine", "datamodel"]
categories = ["parser-implementations"]
readme = "README.md"
exclude = ["tests/*"]

[dependencies]
indexmap = "2.1.0"
regex = "1.10.2"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
